### ISSUE TITLE
Middleware for errors

### ISSUE THREAD

**Issue by Gmarn** [Wolox/express-js-bootstrap#76]
In the middleware for errors there is an issue statusCode definition:
https://github.com/Wolox/express-js-bootstrap/blob/a84c1206f76666e2f6a2b4e77793a3de3bf1cc65/app/middlewares/errors.js#L15

Here the `internalCode` is not define in any error, so is cause undefined and throw a 500.

**Comment by gonziesc** [comment]
Resolved in #78
